# Generated by Django 6.0.2 on 2026-02-11 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentorg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgmember',
            old_name='data_joined',
            new_name='date_joined',
        ),
    ]
