# Generated by Django 6.0.2 on 2026-02-11 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentorg', '0002_rename_data_joined_orgmember_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='upadate_at',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='upadate_at',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='orgmember',
            old_name='upadate_at',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='upadate_at',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='upadate_at',
            new_name='update_at',
        ),
    ]
